/* ============================================================
 * 丑团 · 数据层
 * ------------------------------------------------------------
 * ★ 加朋友:在 friends 数组里加一条即可,搜索/门店/下单全自动生效
 * ★ 加店铺:在 shops 数组里加,logo 用 assets/brands/ 下的品牌图
 * ★ 菜品图标:icon 填 assets/icons/ 下的 dish-*.svg
 * ============================================================ */

const UT_DATA = {

  /* ---------- 基础信息 ---------- */
  appName: "丑团",
  location: "翻斗花园 · 六栋303",
  user: { name: "尊贵的丑团用户", address: "翻斗花园六栋303", phone: "138****8888" },

  /* ==========================================================
   * 朋友 = 商品(玩法保留)
   * 加朋友:照格式往数组加一条 { id 唯一, name, emoji 店铺/商品展示图,
   * price 身价, status 今日状态, tag, desc 食用说明, options 可选规格 },
   * 搜索/门店/下单自动生效;展示图用表情或可爱小动物
   * ========================================================== */
  friends: [
    {
      id: "f1",
      name: "七安",
      emoji: "🐶",           // 萨摩耶小狗
      logoImg: "assets/friends/f_qianan.png",   // 店铺展示图:萨摩耶头部
      dishImg: "assets/friends/f_qianan.png",   // 商品展示图:萨摩耶头部
      price: 88,
      status: "今日可点",
      tag: "好友严选",
      desc: "口感q弹",
      options: [{ name: "规格", choices: [{ label: "标准款", delta: 0 }] }],
    },
    {
      id: "f2",
      name: "段嘉烁",
      emoji: "🐱",           // 小猫
      price: 1,
      status: "限时上架",
      tag: "好友严选",
      desc: "路过的老年人",
      options: [{ name: "规格", choices: [{ label: "别点我", delta: 0 }] }],
    },
    {
      id: "f3",
      name: "阿群",
      emoji: "🤖",           // 机器人
      price: 88,
      status: "今日可点",
      tag: "好友严选",
      desc: "淡淡的像个人机",
      options: [{ name: "规格", choices: [{ label: "就这样", delta: 0 }] }],
    },
    {
      id: "f4",
      name: "周田惟",
      emoji: "🍜",           // 牛肉面
      price: 88,
      status: "皇上驾到",
      tag: "好友严选",
      desc: "皇上驾到",
      options: [{ name: "口味", choices: [{ label: "老板给我来碗忘情牛肉面", delta: 0 }] }],
    },
    {
      id: "f5",
      name: "冰淇淋",
      emoji: "🍦",           // 冰淇淋
      price: 9.9,
      status: "同桌降临",
      tag: "好友严选",
      desc: "同桌降临",
      options: [{ name: "规格", choices: [{ label: "大冰棍", delta: 0 }] }],
    },
    {
      id: "f6",
      name: "易",
      emoji: "🐱",           // 小猫
      logoImg: "assets/friends/f_yi.png",       // 店铺展示图:暹罗猫头部
      dishImg: "assets/friends/f_yi.png",       // 商品展示图:暹罗猫头部
      price: 88,
      status: "今日可点",
      tag: "好友严选",
      desc: "恶魔天使二象性",
      options: [{ name: "规格", choices: [{ label: "乐乐", delta: 0 }] }],
    },
    {
      id: "f7",
      name: "星期",
      emoji: "📅",           // 日历
      price: 88,
      status: "本周热卖",
      tag: "好友严选",
      desc: "小乐乐",
      options: [{ name: "规格", choices: [{ label: "week", delta: 0 }] }],
    },
    {
      id: "f8",
      name: "碗碗",
      emoji: "🥣",           // 碗
      price: 1,
      status: "今日可点",
      tag: "好友严选",
      desc: "一个碗",
      options: [{ name: "规格", choices: [{ label: "🥣", delta: 0 }] }],
    },
  ],

  /* ==========================================================
   * 连锁店铺(真实品牌)
   * deliveryFee: 普通店配送费正常;朋友店故意离谱(恶搞只在计算上)
   * ========================================================== */
  shops: [
    {
      id: "s_kfc",
      name: "肯德基(翻斗花园店)",
      logo: "assets/brands/brand_kfc.png",
      rating: 4.8,
      sales: "月售 9000+",
      tags: ["品牌连锁", "汉堡炸鸡"],
      delivery: "配送 ¥5 · 30 分钟",
      deliveryFee: 5,
      distance: "1.1km",
      notice: "欢迎光临肯德基,炸鸡汉堡现做现卖。",
      menu: [
        { id: "k1", category: "汉堡", name: "香辣鸡腿堡", icon: "assets/dishes/k1.jpg", price: 21.5, sales: "月售 3000+", desc: "招牌经典,香辣过瘾" },
        { id: "k2", category: "汉堡", name: "劲脆鸡腿堡", icon: "assets/dishes/k2.jpg", price: 21.5, sales: "月售 2500+", desc: "酥脆多汁,一口满足" },
        { id: "k3", category: "炸鸡", name: "吮指原味鸡", icon: "assets/dishes/k3.jpg", price: 12, sales: "月售 4000+", desc: "原味秘制,吮指回味" },
        { id: "k4", category: "小食", name: "葡式蛋挞(1只)", icon: "assets/dishes/k4.jpg", price: 8, sales: "月售 5000+", desc: "外酥里嫩,甜而不腻" },
        { id: "k5", category: "小食", name: "薯条(中份)", icon: "assets/dishes/k5.jpg", price: 11, sales: "月售 6000+", desc: "金黄酥脆,现炸出锅" },
        { id: "k6", category: "饮品", name: "冰可乐(中杯)", icon: "assets/dishes/k6.jpg", price: 8, sales: "月售 8000+", desc: "快乐水,配炸鸡更快乐",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }] },
      ],
    },
    {
      id: "s_mcd",
      brandColor: "#DA291C",
      name: "麦当劳(翻斗花园店)",
      logo: "assets/brands/brand_mcd.png",
      rating: 4.7,
      sales: "月售 8000+",
      tags: ["品牌连锁", "汉堡快餐"],
      delivery: "配送 ¥5 · 30 分钟",
      deliveryFee: 5,
      distance: "1.3km",
      notice: "麦当劳中国,为您带来经典美味。",
      menu: [
        { id: "m1", category: "汉堡", name: "巨无霸", icon: "assets/dishes/m1.jpg", price: 25, sales: "月售 2000+", desc: "双层牛肉,经典之选" },
        { id: "m2", category: "汉堡", name: "麦辣鸡腿堡", icon: "assets/dishes/m2.jpg", price: 21, sales: "月售 3000+", desc: "中国限定,香辣过瘾" },
        { id: "m3", category: "汉堡", name: "麦香鱼", icon: "assets/dishes/m3.jpg", price: 20, sales: "月售 800+", desc: "深海鳕鱼,鲜嫩多汁" },
        { id: "m4", category: "小食", name: "薯条(中份)", icon: "assets/dishes/m4.jpg", price: 12, sales: "月售 5000+", desc: "经典黄金薯条" },
        { id: "m5", category: "甜品", name: "麦旋风", icon: "assets/dishes/m5.jpg", price: 12.5, sales: "月售 1500+", desc: "奥利奥碎,冰爽绵密" },
        { id: "m6", category: "饮品", name: "冰可乐(中杯)", icon: "assets/dishes/m6.jpg", price: 8.5, sales: "月售 7000+", desc: "快乐肥宅水",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }] },
      ],
    },
    {
      id: "s_tastine",
      brandColor: "#C8102E",
      name: "塔斯汀·中国汉堡(翻斗花园店)",
      logo: "assets/brands/brand_tastine.png",
      rating: 4.6,
      sales: "月售 6000+",
      tags: ["品牌连锁", "手擀汉堡"],
      delivery: "配送 ¥4 · 35 分钟",
      deliveryFee: 4,
      distance: "1.8km",
      notice: "手擀汉堡胚,现烤现卖,中国胃的选择。",
      menu: [
        { id: "t1", category: "汉堡", name: "香辣鸡腿中国汉堡", icon: "assets/dishes/t1.jpg", price: 18, sales: "月售 3500+", desc: "手擀胚配香辣鸡腿" },
        { id: "t2", category: "汉堡", name: "多汁牛肉中国汉堡", icon: "assets/dishes/t2.jpg", price: 22, sales: "月售 1200+", desc: "厚切牛肉,汁水充盈" },
        { id: "t3", category: "小食", name: "粗薯条", icon: "assets/dishes/t3.jpg", price: 10, sales: "月售 2000+", desc: "粗切薯条,外脆里糯" },
        { id: "t4", category: "小食", name: "上校鸡块(5块)", icon: "assets/dishes/t4.jpg", price: 11, sales: "月售 1800+", desc: "外酥里嫩,蘸酱更香" },
        { id: "t5", category: "饮品", name: "冰可乐(中杯)", icon: "assets/dishes/t5.jpg", price: 7, sales: "月售 4000+", desc: "解腻神器",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }] },
      ],
    },
    {
      id: "s_luckin",
      brandColor: "#0E2C5C",
      name: "瑞幸咖啡(翻斗花园店)",
      logo: "assets/brands/brand_luckin.png",
      rating: 4.9,
      sales: "月售 5000+",
      tags: ["品牌连锁", "咖啡"],
      delivery: "配送 ¥3 · 25 分钟",
      deliveryFee: 3,
      distance: "0.5km",
      notice: "专业咖啡,每天一杯,好咖啡不贵。",
      menu: [
        { id: "l1", category: "咖啡", name: "生椰拿铁", icon: "assets/dishes/l1.jpg", price: 17, sales: "月售 3000+", desc: "椰香浓郁,拿铁丝滑",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "l2", category: "咖啡", name: "标准美式", icon: "assets/dishes/l2.jpg", price: 13, sales: "月售 1000+", desc: "纯粹咖啡香,提神首选",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "l3", category: "咖啡", name: "拿铁", icon: "assets/dishes/l3.jpg", price: 15, sales: "月售 1500+", desc: "奶咖平衡,经典不衰",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "l4", category: "咖啡", name: "陨石拿铁", icon: "assets/dishes/l4.jpg", price: 19, sales: "月售 800+", desc: "黑糖寒天,口感丰富",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_mixue",
      brandColor: "#E31C1C",
      name: "蜜雪冰城(翻斗花园店)",
      logo: "assets/brands/brand_mixue.png",
      rating: 4.5,
      sales: "月售 10000+",
      tags: ["品牌连锁", "茶饮冰淇淋"],
      delivery: "配送 ¥3 · 30 分钟",
      deliveryFee: 3,
      distance: "0.9km",
      notice: "你爱我我爱你,蜜雪冰城甜蜜蜜。",
      menu: [
        { id: "mx1", category: "茶饮", name: "冰鲜柠檬水", icon: "assets/dishes/mx1.jpg", price: 4, sales: "月售 6000+", desc: "性价比之王,酸甜解渴",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "mx2", category: "冰淇淋", name: "摇摇奶昔", icon: "assets/dishes/mx2.jpg", price: 6, sales: "月售 1500+", desc: "摇一摇更好喝",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "mx3", category: "冰淇淋", name: "草莓圣代", icon: "assets/dishes/mx3.jpg", price: 6, sales: "月售 1200+", desc: "草莓果酱配冰淇淋" },
        { id: "mx4", category: "茶饮", name: "珍珠奶茶", icon: "assets/dishes/mx4.jpg", price: 7, sales: "月售 3000+", desc: "经典珍珠,弹弹弹",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_heytea",
      name: "喜茶(翻斗花园店)",
      logo: "assets/brands/brand_heytea.png",
      rating: 4.8,
      sales: "月售 2000+",
      tags: ["品牌连锁", "新茶饮"],
      delivery: "配送 ¥5 · 35 分钟",
      deliveryFee: 5,
      distance: "2.0km",
      notice: "灵感之茶,现制鲜果茶。",
      menu: [
        { id: "h1", category: "水果茶", name: "多肉葡萄", icon: "assets/dishes/h1.jpg", price: 25, sales: "月售 800+", desc: "整颗葡萄,果肉满满",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "h2", category: "水果茶", name: "芝芝莓莓", icon: "assets/dishes/h2.jpg", price: 27, sales: "月售 600+", desc: "芝士奶盖配鲜莓",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "h3", category: "奶茶", name: "烤黑糖波波牛乳", icon: "assets/dishes/h3.jpg", price: 22, sales: "月售 500+", desc: "黑糖珍珠,香浓牛乳",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "h4", category: "奶茶", name: "纯绿妍", icon: "assets/dishes/h4.jpg", price: 13, sales: "月售 400+", desc: "清新绿茶,解腻爽口",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_naixue",
      brandColor: "#B03A3A",
      name: "奈雪的茶(翻斗花园店)",
      logo: "assets/brands/brand_naixue.png",
      rating: 4.7,
      sales: "月售 1500+",
      tags: ["品牌连锁", "新茶饮"],
      delivery: "配送 ¥5 · 35 分钟",
      deliveryFee: 5,
      distance: "2.2km",
      notice: "一杯好茶,一口软欧包。",
      menu: [
        { id: "n1", category: "水果茶", name: "霸气橙子", icon: "assets/dishes/n1.jpg", price: 24, sales: "月售 500+", desc: "整颗橙子,维C满满",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "n2", category: "水果茶", name: "霸气芝士草莓", icon: "assets/dishes/n2.jpg", price: 28, sales: "月售 400+", desc: "芝士奶盖配鲜草莓",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "n3", category: "奶茶", name: "金色山脉宝藏茶", icon: "assets/dishes/n3.jpg", price: 23, sales: "月售 300+", desc: "大红袍茶底,宝藏配料",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "n4", category: "奶茶", name: "杨枝甘露", icon: "assets/dishes/n4.jpg", price: 26, sales: "月售 450+", desc: "芒果西柚,清爽甘甜",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_cudi",
      brandColor: "#0A2C52",
      name: "库迪咖啡(翻斗花园店)",
      logo: "assets/brands/brand_cudi.png",
      rating: 4.6,
      sales: "月售 3000+",
      tags: ["品牌连锁", "咖啡"],
      delivery: "配送 ¥3 · 25 分钟",
      deliveryFee: 3,
      distance: "0.7km",
      notice: "咖啡自由,随时随地。",
      menu: [
        { id: "c1", category: "咖啡", name: "潘帕斯蓝椰拿铁", icon: "assets/dishes/c1.jpg", price: 16, sales: "月售 1200+", desc: "蓝色椰香,颜值担当",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "c2", category: "咖啡", name: "生椰拿铁", icon: "assets/dishes/c2.jpg", price: 14, sales: "月售 1000+", desc: "椰乳咖啡,顺滑香浓",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "c3", category: "咖啡", name: "标准美式", icon: "assets/dishes/c3.jpg", price: 9.9, sales: "月售 800+", desc: "天天 9.9,咖啡自由",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "c4", category: "咖啡", name: "燕麦拿铁", icon: "assets/dishes/c4.jpg", price: 15, sales: "月售 400+", desc: "燕麦奶,轻负担",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_haidilao",
      name: "海底捞火锅(翻斗花园店)",
      logo: "assets/brands/brand_haidilao.png",
      rating: 4.9,
      sales: "月售 3000+",
      tags: ["品牌连锁", "火锅"],
      delivery: "配送 ¥8 · 45 分钟",
      deliveryFee: 8,
      distance: "2.5km",
      notice: "海底捞火锅,服务至上。",
      menu: [
        { id: "hd1", category: "锅底", name: "番茄锅底", icon: "assets/dishes/hd1.jpg", price: 59, sales: "月售 1500+", desc: "酸甜开胃,锅底首选" },
        { id: "hd2", category: "锅底", name: "麻辣锅底", icon: "assets/dishes/hd2.jpg", price: 59, sales: "月售 1200+", desc: "麻辣鲜香,无辣不欢" },
        { id: "hd3", category: "涮品", name: "捞派毛肚", icon: "assets/dishes/hd3.jpg", price: 42, sales: "月售 1000+", desc: "七上八下,脆嫩爽口" },
        { id: "hd4", category: "涮品", name: "招牌虾滑", icon: "assets/dishes/hd4.jpg", price: 38, sales: "月售 900+", desc: "鲜虾手打,Q弹鲜甜" },
        { id: "hd5", category: "涮品", name: "嫩牛肉", icon: "assets/dishes/hd5.jpg", price: 45, sales: "月售 700+", desc: "现切嫩牛,久煮不老" },
      ],
    },
    {
      id: "s_shaxian",
      brandColor: "#C8102E",
      name: "沙县小吃(翻斗花园店)",
      logo: "assets/brands/brand_shaxian.png",
      rating: 4.4,
      sales: "月售 7000+",
      tags: ["国民小吃", "实惠快餐"],
      delivery: "配送 ¥3 · 25 分钟",
      deliveryFee: 3,
      distance: "0.6km",
      notice: "沙县小吃,国民快餐,好吃不贵。",
      menu: [
        { id: "sx1", category: "主食", name: "葱油拌面", icon: "assets/dishes/sx1.jpg", price: 9, sales: "月售 2500+", desc: "葱香四溢,拌一拌更香" },
        { id: "sx2", category: "小吃", name: "蒸饺(6只)", icon: "assets/dishes/sx2.jpg", price: 8, sales: "月售 1800+", desc: "皮薄馅大,一口一个" },
        { id: "sx3", category: "汤品", name: "鲜肉馄饨", icon: "assets/dishes/sx3.jpg", price: 10, sales: "月售 1500+", desc: "汤鲜味美,暖胃暖心" },
        { id: "sx4", category: "汤品", name: "乌鸡汤炖罐", icon: "assets/dishes/sx4.jpg", price: 15, sales: "月售 600+", desc: "慢火炖煮,滋补养生" },
        { id: "sx5", category: "小吃", name: "卤蛋", icon: "assets/dishes/sx5.jpg", price: 2, sales: "月售 3000+", desc: "卤香入味,加餐必备" },
      ],
    },
    {
      id: "s_hls",
      name: "华莱士(翻斗花园店)",
      logo: "assets/brands/brand_hls.png",
      rating: 4.3,
      sales: "月售 6000+",
      tags: ["品牌连锁", "炸鸡汉堡"],
      delivery: "配送 ¥4 · 30 分钟",
      deliveryFee: 4,
      distance: "1.5km",
      notice: "华莱士,炸鸡汉堡快餐,实惠又美味。",
      menu: [
        { id: "w1", category: "汉堡", name: "香辣鸡腿堡", icon: "assets/dishes/w1.jpg", price: 12, sales: "月售 3000+", desc: "实惠大个,香辣过瘾" },
        { id: "w2", category: "炸鸡", name: "蜜汁手扒鸡", icon: "assets/dishes/w2.jpg", price: 29.9, sales: "月售 1500+", desc: "整只鸡,蜜汁入味" },
        { id: "w3", category: "小食", name: "薯条(中份)", icon: "assets/dishes/w3.jpg", price: 8, sales: "月售 2000+", desc: "金黄酥脆" },
        { id: "w4", category: "炸鸡", name: "香辣鸡翅(2只)", icon: "assets/dishes/w4.jpg", price: 9, sales: "月售 1800+", desc: "外酥里嫩,微辣" },
      ],
    },
    {
      id: "s_zhengxin",
      brandColor: "#C8102E",
      name: "正新鸡排(翻斗花园店)",
      logo: "assets/brands/brand_zhengxin.png",
      rating: 4.5,
      sales: "月售 5000+",
      tags: ["品牌连锁", "炸鸡小吃"],
      delivery: "配送 ¥4 · 25 分钟",
      deliveryFee: 4,
      distance: "1.0km",
      notice: "正新鸡排,好吃不贵,现炸现卖。",
      menu: [
        { id: "z1", category: "炸鸡", name: "香辣鸡排", icon: "assets/dishes/z1.jpg", price: 13, sales: "月售 3000+", desc: "整块鸡排,现炸金黄" },
        { id: "z2", category: "炸鸡", name: "脆皮鸡腿", icon: "assets/dishes/z2.jpg", price: 10, sales: "月售 1500+", desc: "外皮酥脆,肉嫩多汁" },
        { id: "z3", category: "小食", name: "烤鸡脖", icon: "assets/dishes/z3.jpg", price: 8, sales: "月售 800+", desc: "秘制酱料,越啃越香" },
        { id: "z4", category: "小食", name: "骨肉相连(2串)", icon: "assets/dishes/z4.jpg", price: 6, sales: "月售 1200+", desc: "鸡肉脆骨,串串香" },
      ],
    },
    {
      id: "s_lzlsf",
      name: "柳州螺蛳粉(翻斗花园店)",
      logo: "TEXT:柳州螺蛳粉",
      brandColor: "#8B4513",
      rating: 4.6,
      sales: "月售 4500+",
      tags: ["地道风味", "米粉"],
      delivery: "配送 ¥4 · 30 分钟",
      deliveryFee: 4,
      distance: "1.4km",
      notice: "柳州正宗螺蛳粉,酸辣鲜香,闻着臭吃着香。",
      menu: [
        { id: "lsf1", category: "粉面", name: "招牌螺蛳粉", icon: "assets/dishes/lsf1.jpg", price: 13, sales: "月售 2000+", desc: "酸笋螺肉,汤底浓郁",
        options: [{ name: "辣度", choices: [{ label: "不辣", delta: 0 }, { label: "微辣", delta: 0 }, { label: "中辣", delta: 0 }, { label: "特辣", delta: 0 }] }] },
        { id: "lsf2", category: "粉面", name: "干捞螺蛳粉", icon: "assets/dishes/lsf2.jpg", price: 14, sales: "月售 800+", desc: "无汤版,拌着吃更香",
        options: [{ name: "辣度", choices: [{ label: "不辣", delta: 0 }, { label: "微辣", delta: 0 }, { label: "中辣", delta: 0 }, { label: "特辣", delta: 0 }] }] },
        { id: "lsf3", category: "小食", name: "炸蛋", icon: "assets/dishes/lsf3.jpg", price: 3, sales: "月售 1500+", desc: "炸蛋吸汤,灵魂搭配" },
        { id: "lsf4", category: "小食", name: "卤鸭脚(2只)", icon: "assets/dishes/lsf4.jpg", price: 6, sales: "月售 600+", desc: "卤香入味,一嗦脱骨" },
        { id: "lsf5", category: "饮品", name: "招牌冰粉", icon: "assets/dishes/lsf5.jpg", price: 5, sales: "月售 400+", desc: "解辣神器,冰冰凉凉",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_manting",
      name: "满记甜品(翻斗花园店)",
      logo: "TEXT:满记甜品",
      brandColor: "#6A4FA3",
      rating: 4.7,
      sales: "月售 2000+",
      tags: ["港式甜品", "人气甜品"],
      delivery: "配送 ¥5 · 35 分钟",
      deliveryFee: 5,
      distance: "2.1km",
      notice: "港式糖水甜品,杨枝甘露的鼻祖。",
      menu: [
        { id: "mt1", category: "甜品", name: "杨枝甘露", icon: "assets/dishes/mt1.jpg", price: 22, sales: "月售 800+", desc: "芒果西柚西米,经典招牌",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "mt2", category: "甜品", name: "芒果班戟", icon: "assets/dishes/mt2.jpg", price: 19, sales: "月售 500+", desc: "薄皮大馅,入口即化",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "mt3", category: "甜品", name: "双皮奶", icon: "assets/dishes/mt3.jpg", price: 15, sales: "月售 600+", desc: "奶香浓郁,滑嫩细腻",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "mt4", category: "甜品", name: "榴莲忘返", icon: "assets/dishes/mt4.jpg", price: 25, sales: "月售 300+", desc: "榴莲控必点,真材实料",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
    {
      id: "s_85c",
      name: "85度C(翻斗花园店)",
      logo: "TEXT:85度C",
      brandColor: "#C62828",
      rating: 4.5,
      sales: "月售 1800+",
      tags: ["烘焙咖啡", "人气面包"],
      delivery: "配送 ¥5 · 30 分钟",
      deliveryFee: 5,
      distance: "1.9km",
      notice: "面包烘焙 + 咖啡,下午茶好去处。",
      menu: [
        { id: "85c1", category: "面包", name: "凯撒大帝", icon: "assets/dishes/85c1.jpg", price: 12, sales: "月售 700+", desc: "人气咸口面包,料足味美" },
        { id: "85c2", category: "饮品", name: "海岩咖啡", icon: "assets/dishes/85c2.jpg", price: 15, sales: "月售 400+", desc: "咸香奶盖配咖啡,招牌饮品",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
        { id: "85c3", category: "甜品", name: "芝士蛋糕", icon: "assets/dishes/85c3.jpg", price: 18, sales: "月售 500+", desc: "浓郁芝士,绵密口感" },
        { id: "85c4", category: "甜品", name: "鲜奶泡芙", icon: "assets/dishes/85c4.jpg", price: 13, sales: "月售 450+", desc: "外酥内滑,奶香爆浆",
        options: [{ name: "杯型", choices: [{ label: "中杯", delta: 0 }, { label: "大杯", delta: 3 }] }, { name: "糖度", choices: [{ label: "三分糖", delta: 0 }, { label: "半糖", delta: 0 }, { label: "全糖", delta: 0 }] }, { name: "温度", choices: [{ label: "冰", delta: 0 }, { label: "热", delta: 0 }] }] },
      ],
    },
  ],

  /* ==========================================================
   * 优惠券(结算页可选)
   * amount: 减免金额, min: 使用门槛(订单商品金额)
   * ========================================================== */
  coupons: [
    { id: "cp1", amount: 3, min: 0, name: "无门槛红包", desc: "直接抵扣 ¥3" },
    { id: "cp2", amount: 5, min: 30, name: "满 30 减 5", desc: "全场通用" },
    { id: "cp3", amount: 10, min: 50, name: "满 50 减 10", desc: "全场通用" },
    { id: "cp4", amount: 20, min: 100, name: "满 100 减 20", desc: "全场通用" },
    { id: "cp5", amount: 88, min: 999, name: "满 999 减 88", desc: "凑单凑到破产" },
  ],

  /* ==========================================================
   * 文案区(界面文案正常化;恶搞只保留在价格/金额计算环节)
   * ========================================================== */
  texts: {
    searchEmpty: "未找到相关店铺\n换个关键词试试吧",
    searchFriendPrefix: "为您找到相关好友",
    notOpen: "该分类即将上线\n敬请期待",
    redpacket: {
      title: "红包领取成功",
      body: "¥10 无门槛红包已放入您的卡包\n(有效期:永久,限本平台使用)",
      btn: "好的",
    },
    cartEmpty: "购物车还是空的\n去选点好吃的吧",
    coupon: "满 100 减 15\n全场通用,限使用 1 张",
    payOk: "支付成功!",
    deliveryDone: {
      normal: "您实付的金额已原路退回(退回失败)\n资金已自动捐赠给丑团慈善基金会,感谢您的慷慨",
      friend: "您的朋友已\"送达\"\n他本人拒绝被配送,正在楼下等你。配送费已从您账户扣除(扣款失败,余额不足)",
    },
    myPage: "登录后可查看您的订单与优惠",
    orderPage: "暂无订单\n快去点一份吧",
    youxuan: "丑团优选\n为您精选每日好物",
  },

  /* 配送进度提示(逼真化) */
  riderSteps: [
    "骑手已接单,正在前往商家…",
    "骑手已取餐,正在配送…",
    "骑手距您约 500 米…",
    "骑手距您约 100 米…",
    "骑手即将送达…",
    "已送达!",
  ],
};
